### ISSUE TITLE
problem in utils.py

### ISSUE THREAD

**Issue by sonkite225** [omkarcloud/chromedriver-autoinstaller-fix#1]
1st: thx for the fix :)

2nd a little strange prob.

when i start a script with autoinst in it this error occurs:

File "C:\Users\*****\anaconda3\lib\site-packages\chromedriver_autoinstaller_fix\utils.py", line 166, in get_chrome_version
    dirs = [f.name for f in os.scandir("C:\\Program Files\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
    
so i had to open the utils.py and change this:

    elif platform == "win":
        # check both of Program Files and Program Files (x86).
        # if the version isn't found on both of them, version is an empty string.
        dirs = [f.name for f in os.scandir("C:\\Program Files\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
        if dirs:
            version = max(dirs)
        else:
            dirs = [f.name for f in os.scandir("C:\\Program Files (x86)\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
            version = max(dirs) if dirs else ''
            
to that:

    elif platform == "win":
        # check both of Program Files and Program Files (x86).
        # if the version isn't found on both of them, version is an empty string.
        dirs = [f.name for f in os.scandir("C:\\Program Files (x86)\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
        if dirs:
            version = max(dirs)
        else:
            dirs = [f.name for f in os.scandir("C:\\Program Files\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
            version = max(dirs) if dirs else ''
            

(put the x86 program files folder, where my chrome is in, first. then it works.
but it would be way better when the utils get this shit done by itself ^^

**Comment by Chetan11-dev** [comment]
Thanks, Fixed!

**Comment by sonkite225** [comment]
great, thx :)

**Comment by Chetan11-dev** [comment]
Welcome
